# Meta

title: "Graham Macphee"
description: ""
keywords: ""
author: gmph
image: "/assets/img/graham.png"
twitter:
  username: gmph
facebook:
  admins: 100000408177137
fb_author : "100000408177137"  

# Helpers

url: localhost:4000
enforce_ssl: localhost:4000
locale: "en_GB"
permalink: /:title
excerpt_separator: "<!--MORE-->"

# Defaults

defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      author: 
        name: Graham Macphee
        email: hi@grahammacphee.com
        uri: https://grahammacphee.com
        twitter : gmph
        picture: /assets/img/graham.png
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is-post: true # automatically set is_post=true for all posts

# Plugins

plugins:
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-seo-tag
jekyll-mentions: https://twitter.com
sass:
    sass_dir: _styles

exclude: [ 'Gemfile*', '_site/', '.sass-cache/', '.vscode/' ]