title: "Graham Macphee"
url: https://gmph.co
enforce_ssl: gmph.co
author: "Graham Macphee"
fb_author : "100000408177137"
locale: "en_GB"
permalink: /:title
excerpt_separator: "<!--MORE-->"
defaults:
  -
    scope:
      path: "" # all files in the project
    values:
      author: {"name": "Graham Macphee", "email": "hi@gmph.co", "uri": "http://gmph.co", "twitter" : "gmph"}
gems:
  - jekyll-redirect-from
  - jekyll-mentions
jekyll-mentions: https://twitter.com
sass:
    sass_dir: assets/css